name: BPF Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/bpf-test.yml"

permissions: read-all

jobs:
  bpf_tests:
    name: BPF Unit Test
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        env:
        - VERSION: 15
        - VERSION: 16
        - VERSION: 17
        - VERSION: 18
        - VERSION: 19

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Dependencies
        env: ${{ matrix.env }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-$VERSION llvm-$VERSION

      - name: Run BPF tests
        env: ${{ matrix.env }}
        run: |
          set -o pipefail
          git submodule update --init
          sudo CLANG=clang-$VERSION make ebpf-test 2>&1 | tee bpf-test-clang-$VERSION.log

      - name: Upload BPF test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bpf-test-logs-clang-${{ matrix.env.VERSION }}
          path: bpf-test-clang-*.log
          if-no-files-found: ignore
          retention-days: 7
